### ISSUE TITLE
LA - Taco Trucks only?

### ISSUE THREAD

**Issue by matikin9** [hunterowens/the_great_taco_hunt#5]
I noticed the file name is "tacotrucks.md", is the plan to put non-trucks in a separate file?

**Comment by hunterowens** [comment]
Yes, I should break it out.

**Comment by hunterowens** [comment]
Also most of this list was written approx when I left Los Angeles in
2011...

**Comment by matikin9** [comment]
I'm always excited for food-related projects!  :smile:

**Comment by hunterowens** [comment]
:taco: See #6. Closing.
